/* DO NOT EDIT, FILE GENERATED BY COREMAKE */

#include "matroska/matroska2_init.h"
#include "matroska2_project.h"

#include "ebml/ebml2_init.h"
#include <ebml/corec/err.h>
#include <assert.h>
extern const nodemeta Matroska_Class[];

err_t MATROSKA_RegisterAll(nodemodule* Module)
{
    int err = EBML_RegisterAll(Module);
    if(err) return err;
	NodeRegisterClassEx(Module,Matroska_Class);
    MATROSKA_InitMeta(Module);
	return ERR_NONE;
}

void MATROSKA_UnRegisterAll(nodemodule* Module)
{
    EBML_UnRegisterAll(Module);
}


void MATROSKA_InitMeta(nodecontext* p)
{
    EBML_InitMeta(p);
#ifdef PROJECT_FOURCC
    fourcc_t FourCC = PROJECT_FOURCC;
    Node_Set(p,NODECONTEXT_PROJECT_FOURCC,&FourCC,sizeof(FourCC));
#endif
#ifdef PROJECT_NAME
    Node_SetData((node*)p,NODECONTEXT_PROJECT_NAME,TYPE_STRING,PROJECT_NAME);
#endif
#ifdef PROJECT_VENDOR
    Node_SetData((node*)p,NODECONTEXT_PROJECT_VENDOR,TYPE_STRING,PROJECT_VENDOR);
#endif
#ifdef PROJECT_HELP
    Node_SetData((node*)p,NODECONTEXT_PROJECT_HELP,TYPE_STRING,PROJECT_HELP);
#endif
#ifdef PROJECT_VERSION
    Node_SetData((node*)p,NODECONTEXT_PROJECT_VERSION,TYPE_STRING,PROJECT_VERSION);
#endif
#ifdef PROJECT_BUILD
    {
        int BuildVersion = PROJECT_BUILD;
        Node_Set(p,NODECONTEXT_PROJECT_BUILD,&BuildVersion,sizeof(BuildVersion));
    }
#endif
#ifdef PROJECT_MIME
    Node_SetData((node*)p,NODECONTEXT_PROJECT_MIME,TYPE_STRING,PROJECT_MIME);
#endif
#ifdef PROJECT_APPID
    {
        uint16_t AppId = PROJECT_APPID;
        Node_Set(p,NODECONTEXT_PROJECT_APPID,&AppId,sizeof(AppId));
    }
#endif
#ifdef PROJECT_PATH
    Node_SetData((node*)p,NODECONTEXT_PROJECT_PATH,TYPE_STRING,PROJECT_PATH);
#endif
}
