/* DO NOT EDIT, FILE GENERATED BY COREMAKE */

#include <ebml/ebml2_init.h>
#include "ebml2_project.h"
#include <ebml/corec/err.h>

#include <assert.h>


extern const nodemeta EBMLElement_Class[];
extern const nodemeta EBMLMaster_Class[];
extern const nodemeta EBMLBinary_Class[];
extern const nodemeta EBMLString_Class[];
extern const nodemeta EBMLInteger_Class[];
extern const nodemeta EBMLCRC_Class[];
extern const nodemeta EBMLDate_Class[];
extern const nodemeta EBMLVoid_Class[];
extern const nodemeta BufStream_Class[];
extern const nodemeta MemStream_Class[];
extern const nodemeta Streams_Class[];
extern const nodemeta File_Class[];
extern const nodemeta FileDb_Class[];
extern const nodemeta VFS_Class[];
extern const nodemeta Stdio_Class[];
extern const nodemeta LangStr_Class[];
extern const nodemeta UrlPart_Class[];
extern void FileXio_Init(nodemodule* Module);
extern void FileXio_Done(nodemodule* Module);

err_t EBML_RegisterAll(nodemodule* Module)
{
#if !defined(CONFIG_EBML2_LIB)
	NodeRegisterClassEx(Module,BufStream_Class);
	NodeRegisterClassEx(Module,MemStream_Class);
	NodeRegisterClassEx(Module,Streams_Class);
#endif
#if (!defined(CONFIG_EBML2_LIB) && defined(TARGET_WIN) && defined(TARGET_WIN)) || (!defined(CONFIG_EBML2_LIB) && defined(TARGET_SYMBIAN) && defined(TARGET_SYMBIAN)) || (!defined(CONFIG_EBML2_LIB) && defined(TARGET_PS2SDK) && \
    defined(TARGET_PS2SDK)) || (!defined(CONFIG_EBML2_LIB) && defined(TARGET_PALMOS) && defined(TARGET_PALMOS)) || (!defined(CONFIG_EBML2_LIB) && (defined(TARGET_LINUX) || defined(TARGET_OSX) || defined(TARGET_ANDROID) || \
    defined(TARGET_LINUX) || defined(TARGET_OSX) || defined(TARGET_ANDROID)) && (defined(TARGET_LINUX) || defined(TARGET_OSX) || defined(TARGET_ANDROID) || defined(TARGET_LINUX) || defined(TARGET_OSX) || \
    defined(TARGET_ANDROID)))
	NodeRegisterClassEx(Module,File_Class);
#endif
#if !defined(CONFIG_EBML2_LIB) && defined(TARGET_PALMOS) && defined(TARGET_PALMOS)
	NodeRegisterClassEx(Module,FileDb_Class);
	NodeRegisterClassEx(Module,VFS_Class);
#endif
#if !defined(CONFIG_EBML2_LIB) && defined(TARGET_PS2SDK) && defined(TARGET_PS2SDK)
	FileXio_Init(Module);
#endif
#if !defined(CONFIG_EBML2_LIB) && ((defined(CONFIG_STDIO) && !defined(TARGET_PALMOS)) || (defined(CONFIG_STDIO) && !defined(TARGET_PALMOS))) && ((defined(CONFIG_STDIO) && !defined(TARGET_PALMOS)) || (defined(CONFIG_STDIO) && \
    !defined(TARGET_PALMOS)))
	NodeRegisterClassEx(Module,Stdio_Class);
#endif
	NodeRegisterClassEx(Module,EBMLElement_Class);
	NodeRegisterClassEx(Module,EBMLMaster_Class);
	NodeRegisterClassEx(Module,EBMLBinary_Class);
	NodeRegisterClassEx(Module,EBMLString_Class);
	NodeRegisterClassEx(Module,EBMLInteger_Class);
	NodeRegisterClassEx(Module,EBMLCRC_Class);
	NodeRegisterClassEx(Module,EBMLDate_Class);
	NodeRegisterClassEx(Module,EBMLVoid_Class);
#if !defined(CONFIG_EBML2_LIB)
	NodeRegisterClassEx(Module,LangStr_Class);
	NodeRegisterClassEx(Module,UrlPart_Class);
#endif
	return ERR_NONE;
}

void EBML_UnRegisterAll(nodemodule* Module)
{
#if !defined(CONFIG_EBML2_LIB) && defined(TARGET_PS2SDK) && defined(TARGET_PS2SDK)
	FileXio_Done(Module);
#endif
}


void EBML_InitMeta(nodecontext* p)
{
#ifdef PROJECT_FOURCC
    fourcc_t FourCC = PROJECT_FOURCC;
    Node_Set(p,NODECONTEXT_PROJECT_FOURCC,&FourCC,sizeof(FourCC));
#endif
#ifdef PROJECT_NAME
    Node_SetData((node*)p,NODECONTEXT_PROJECT_NAME,TYPE_STRING,PROJECT_NAME);
#endif
#ifdef PROJECT_VENDOR
    Node_SetData((node*)p,NODECONTEXT_PROJECT_VENDOR,TYPE_STRING,PROJECT_VENDOR);
#endif
#ifdef PROJECT_HELP
    Node_SetData((node*)p,NODECONTEXT_PROJECT_HELP,TYPE_STRING,PROJECT_HELP);
#endif
#ifdef PROJECT_VERSION
    Node_SetData((node*)p,NODECONTEXT_PROJECT_VERSION,TYPE_STRING,PROJECT_VERSION);
#endif
#ifdef PROJECT_BUILD
    {
        int BuildVersion = PROJECT_BUILD;
        Node_Set(p,NODECONTEXT_PROJECT_BUILD,&BuildVersion,sizeof(BuildVersion));
    }
#endif
#ifdef PROJECT_MIME
    Node_SetData((node*)p,NODECONTEXT_PROJECT_MIME,TYPE_STRING,PROJECT_MIME);
#endif
#ifdef PROJECT_APPID
    {
        uint16_t AppId = PROJECT_APPID;
        Node_Set(p,NODECONTEXT_PROJECT_APPID,&AppId,sizeof(AppId));
    }
#endif
#ifdef PROJECT_PATH
    Node_SetData((node*)p,NODECONTEXT_PROJECT_PATH,TYPE_STRING,PROJECT_PATH);
#endif
}
