/* DO NOT EDIT, FILE GENERATED BY COREMAKE */

#include "corec/node.h"
#include "ebml.h"

#ifdef __cplusplus
extern "C" {
#endif

EBML_DLL extern err_t EBML_RegisterAll(nodemodule* Module);
EBML_DLL extern void EBML_UnRegisterAll(nodemodule* Module);
EBML_DLL extern void EBML_InitMeta(nodecontext* p);

#ifdef __cplusplus
}
#endif
