/* DO NOT EDIT, FILE GENERATED BY COREMAKE */

#include "../ebml/corec/node.h"
#include "matroska.h"

#ifdef __cplusplus
extern "C" {
#endif

MATROSKA_DLL extern err_t MATROSKA_RegisterAll(nodemodule* Module);
MATROSKA_DLL extern void MATROSKA_UnRegisterAll(nodemodule* Module);
MATROSKA_DLL extern void MATROSKA_InitMeta(nodecontext* p);

#ifdef __cplusplus
}
#endif
