//#define COREMAKE_STATIC
//#define COREMAKE_UNICODE
#define CONFIG_EBML_WRITING
//#define CONFIG_EBML_UNICODE
#define HAVE_EBML2
#define CONFIG_ZLIB
#define CONFIG_MATROSKA2
//#define USE_PRECOMPILED_HEADERS
//#define CONFIG_DEBUGCHECKS
#define CONFIG_STDIO
#define CONFIG_FILEPOS_64
#define COREMAKE_CONFIG_HELPER
//#define CONFIG_DEBUG_LEAKS

#ifndef COREMAKE_STATIC
#ifdef _USE_DLL
#define STR_IMPORTS
#define ARRAY_IMPORTS
#define DATE_IMPORTS
#define FILE_IMPORTS
#define EBML_IMPORTS
#define MATROSKA2_IMPORTS
#define MD5_IMPORTS
#else
#define STR_EXPORTS
#define ARRAY_EXPORTS
#define DATE_EXPORTS
#define FILE_EXPORTS
#define EBML_EXPORTS
#define MATROSKA2_EXPORTS
#define MD5_EXPORTS
#endif
#endif