name: "Build tools"
on:
  pull_request:
    paths-ignore:
      - 'spectool/**'

jobs:
  build_tools:
    name: Build all tools for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
          - os: ubuntu-latest
            triplet: x64-linux
            CMAKE_CC: CC=gcc-14
          - os: macos-latest
            triplet: x64-osx
    env:
      CMAKE_OPTIONS: -DDEV_MODE=ON
    steps:
      - name: list compilers
        if: ${{ contains(matrix.os, 'ubuntu') }}
        run: dpkg --list | grep compiler

      - name: Get pushed code
        uses: actions/checkout@v4

      - name: Configure CMake
        run: ${{ matrix.CMAKE_CC }} cmake -S . -B _build ${{ env.CMAKE_OPTIONS }}

      - name: Build with CMake
        run: cmake --build _build --config Debug --parallel

      - name: Test installation
        run: |
          cmake --install _build --config Debug --prefix _built
