name: "Tool binaries"
on: 
  push:
    branches:
      - master
  release:
  # pull_request: # ^ for testing

jobs:
  build_tools_win32:
    name: Build all binaries for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
          # - os: ubuntu-latest
          #   triplet: x64-linux
          # - os: macos-latest
          #   triplet: x64-osx
    steps:
      - name: Get pushed code
        uses: actions/checkout@v3

      - uses: lukka/get-cmake@latest

      - name: Configure CMake 
        run: cmake -S . -B _build

      - name: Build Release
        run: cmake --build _build --config Release --parallel

      - name: Generate mkclean artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mkclean-${{ matrix.os }}
          path: _build/mkclean/pkg_bin

      - name: Generate mkvalidator artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mkvalidator-${{ matrix.os }}
          path: _build/mkvalidator/pkg_bin
