name: "Build tools"
on:
  pull_request:
    paths-ignore:
      - 'spectool/**'

jobs:
  build_tools:
    name: Build all tools for ${{ matrix.target.os }} ${{ matrix.target.cmake_env }}
    runs-on: ${{ matrix.target.os }}
    strategy:
      fail-fast: false
      matrix:
        target: [
          {"os": "ubuntu-latest", "cmake_env": "CC=gcc-14"},
          {"os": "ubuntu-latest", "cmake_env": "CC=clang-18"},
          {"os": "ubuntu-20.04",  "cmake_env": "CC=gcc-9"},
          {"os": "ubuntu-20.04",  "cmake_env": "CC=clang-10"},
          {"os": "macos-latest"  },
          {"os": "windows-latest"},
        ]
        include:
          - os: windows-latest
            triplet: x64-windows
          - os: ubuntu-latest
            triplet: x64-linux
          - os: ubuntu-20.04
            triplet: x64-linux
          - os: macos-latest
            triplet: x64-osx
    env:
      CMAKE_OPTIONS: -DDEV_MODE=ON
      CMAKE_ENV: ${{ matrix.target.cmake_env }}
    steps:
      - name: list compilers
        if: ${{ contains(matrix.target.os, 'ubuntu') }}
        run: dpkg --list | grep compiler

      - name: Get pushed code
        uses: actions/checkout@v4

      - name: Configure CMake
        run: ${{ env.CMAKE_ENV }} cmake -S . -B _build ${{ env.CMAKE_OPTIONS }}

      - name: Build with CMake
        run: cmake --build _build --config Debug --parallel

      - name: Test installation
        run: |
          cmake --install _build --config Debug --prefix _built
